temperature = ['icy','cool','warm','hot','molten']
aridity = ['arid','dry','balanced','wet','soaked']
terrain = ['flat','shelved','hilly','mountainous','jagged']
flora = ['deserted','brush','thickets','fungal','forested','tangled']
fauna = ['magical','calm','wild','dangerous','evil']

# Mod: Biome: [temperature, aridity, terrain, flora, fauna]
biomes = {
    'BOP': {
        'Alps': ['icy','dry','jagged','deserted','calm']
        'Arctic': ['icy','dry','flat','deserted','calm'],
        'Bamboo Forest': ['hot','balanced','flat','tangled','wild'],
        'Bayou': ['warm','soaked','flat','tangled','dangerous'],
        'Bloody Heap': [],
        'Bog': ['hot','wet','flat','thickets','dangerous'],
        'Boreal Forest': ['cool','balanced','mountainous','forested','calm'],
        'Brushland': ['hot','dry','flat','thickets','dangerous'],
        'Canyon': ['hot','dry','jagged','thickets','dangerous'],
        'Chaparral': ['warm','dry','hilly','brush','calm'],
        'Cherry Blossom Grove': ['cool','balanced','hilly','thickets','magical'],
        'Coniferous Forest': ['warm','balanced','hilly','forested','wild'],
        'Crag': ['cool','arid','jagged','deserted','dangerous'],
        'Dead Forest': ['cool','balanced','hilly','forested','evil'],
        'Dead Swamp': ['warm','wet','flat','thickets','evil'],
        'Deciduous Forest': ['warm','balanced','hilly','forested','wild'],
        'Dunes': ['hot','dry','jagged','deserted','dangerous'],
        'Fen': ['warm','wet','hilly','thickets','dangerous'],
        'Flower Field': ['warm','balanced','shelved','brush','magical'],
        'Frost Forest': ['icy','balanced','hilly','forested','wild'],
        'Grassland': ['cool','wet','hilly','brush','calm'],
        'Grove': ['cool','balanced,','flat','thickets','calm'],
        'Heathland': ['warm','dry','flat','brush','calm'],
        'Highland': ['warm','dry','jagged','brush','calm'],
        'Jade Cliffs': ['warm','balanced','jagged','forested','wild'],
        'Lavender Fields': ['warm','balanced','flat','brush','calm'],
        'Lush Desert': ['hot','dry','hilly','brush','dangerous'],
        'Lush Swamp': ['warm','soaked','hilly','thickets','dangerous'],
        'Maple Woods': ['cool','balanced','hilly','forested','calm'],
        'Marsh': ['warm','soaked','hilly','brush','wild'],
        'Meadow': ['cool','balanced','flat','brush','calm'],
        'Moor': ['cool','wet','mountainous','brush','wild'],
        'Mountain': ['warm','balanced','mountainous','thickets','calm'],
        'Mystic Grove': ['warm','wet','flat','forested','magical'],
        'Ominous Woods': ['cool','wet','hilly','forested','evil'],
        'Origin Valley': ['warm','balanced','hilly','thickets','magical'],
        'Outback': ['hot','dry','hilly','brush','wild'],
        'Pasture': ['warm','balanced','flat','brush','calm'],
        'Prairie': ['warm','dry','flat','thickets','calm'],
        'Quagmire': ['warm','wet','flat','brush','evil'],
        'Rainforest': ['warm','wet','jagged','tangled','wild'],
        'Redwood Forest': ['warm','balanced','flat','thickets','wild'],
        'Sacred Springs': ['warm','wet','mountainous','forested','magical'],
        'Seasonal Forest': ['cool','balanced','mountainous','forested','wild'],
        'Shield': ['cool','dry','hilly','thickets','dangerous'],
        'Shrubland': ['cool','dry','flat','brush',],
        'Silkglades': ['cool','balanced','flat','tangled','evil'],
        'Sludgepit': ['warm','balanced','flat','forested','evil'],
        'Snowy Coniferous Forest': ['icy','balanced','hilly','forested','wild'],
        'Spruce Woods': ['warm','balanced','flat','forested','wild'],
        'Temperate Rainforest': ['warm','balanced','mountainous','forested','wild'],
        'Thicket': ['cool','dry','flat','brush','calm'],
        'Timber': ['cool','dry','hilly','forested','calm'],
        'Tropical Rainforest': ['hot','wet','hilly','forested','wild'],
        'Tropics': ['hot','balanced','hilly','thickets','wild'],
        'Tundra': ['cool','dry','flat','thickets','wild'],
        'Volcano': ['molten','dry','mountainous','deserted','dangerous'],
        'Wasteland': ['hot','arid','flat','brush','evil'],
        'Wetland': ['warm','wet','hilly','tangled','dangerous'],
        'Woodland': ['warm','balanced','hilly','forested','calm']
    },
    'MC': {
        'Beach': ['warm','balanced','flat','deserted','calm'],
        'Birch Forest': ['cool','balanced','flat','forested','calm'],
        'Birch Forest Hills': ['cool','balanced','hilly','forested','wild'],
        'Birch Forest Hills M': ['cool','balanced','mountainous','forested','wild'],
        'Birch Forest M': ['cool','balanced','hilly','forested','wild'],
        'Cold Beach': ['cool','balanced','flat','deserted','calm'],
        'Cold Taiga': ['icy','balanced','hilly','forested','wild'],
        'Cold Taiga Hills': ['icy','balanced','mountainous','forested','wild'],
        'Cold Taiga M': ['icy','balanced','hilly','forested','calm'],
        'Deep Ocean': ['warm','soaked','flat','deserted','calm'],
        'Desert': ['hot','arid','flat','deserted','calm'],
        'Desert M': ['hot','arid','hilly','deserted','wild'],
        'DesertHills': ['hot','arid','hilly','deserted','wild'],
        'Extreme Hills': ['cool','dry','mountainous','deserted','calm'],
        'Extreme Hills Edge': ['cool','dry','mountainous','deserted','calm'],
        'Extreme Hills M': ['cool','dry','jagged','deserted','calm'],
        'Extreme Hills+': ['cool','dry','mountainous','thickets','calm'],
        'Extreme Hills+ M': ['cool','dry','jagged','thickets','calm'],
        'Flower Forest': ['warm','balanced','hilly','forested','calm'],
        'Forest': ['cool','balanced','hilly','forested','wild'],
        'ForestHills': ['cool','balanced','mountainous','forested','wild'],
        'FrozenOcean': ['icy','soaked','flat','deserted','dangerous'],
        'FrozenRiver': ['icy','balanced','flat','deserted','wild'],
        'Hell': ['molten','arid','jagged','deserted','evil'],
        'Ice Mountains': ['icy','dry','mountainous','deserted','wild'],
        'Ice Plains': ['icy','dry','flat','deserted','wild'],
        'Ice Plains Spikes': ['icy','dry','hilly','deserted','magical'],
        'Jungle': ['hot','wet','hilly','tangled','dangerous'],
        'Jungle M': ['hot','wet','mountainous','tangled','dangerous'],
        'JungleEdge': ['hot','wet','hilly','thickets','dangerous'],
        'JungleEdge M': ['hot','wet','mountainous','thickets','dangerous'],
        'JungleHills': ['hot','wet','mountainous','tangled','dangerous'],
        'Mega Spruce Taiga': ['cool','balanced','hilly','forested','wild'],
        'Mega Taiga': ['cool','balanced','hilly','forested','wild'],
        'Mega Taiga Hills': ['cool','balanced','mountainous','forested','wild'],
        'Mesa': ['hot','arid','shelved','deserted','dangerous'],
        'Mesa (Bryce)': ['hot','arid','jagged','deserted','dangerous'],
        'Mesa Plateau': ['hot','arid','shelved','brush','wild'],
        'Mesa Plateau F': ['hot','arid','shelved','thickets','wild'],
        'Mesa Plateau F M': ['hot','arid','jagged','thickets','wild'],
        'Mesa Plateau M': ['hot','arid','jagged','brush','wild'],
        'MushroomIsland': ['magical','balanced','hilly','fungal','calm'],
        'MushroomIslandShore': ['magical','balanced','flat','fungal','calm'],
        'Ocean': ['cool','soaked','flat','deserted','wild'],
        'Plains': ['cool','balanced','flat','brush','calm'],
        'River': ['cool','balanced','flat','deserted','wild'],
        'Roofed Forest': ['warm','wet','flat','tangled','dangerous'],
        'Roofed Forest M': ['warm','wet','hilly','tangled','dangerous'],
        'Savanna': ['hot','dry','flat','brush','dangerous'],
        'Savanna M': ['hot','dry','hilly','brush','dangerous'],
        'Savanna Plateau': ['hot','dry','shelved','brush','wild'],
        'Savanna Plateau M': ['hot','dry','jagged','brush','wild'],
        'Sky': [],
        'Stone Beach': ['cool','dry','jagged','deserted','calm'],
        'Sunflower Plains': ['warm','balanced','flat','brush','calm'],
        'Swampland': ['warm','soaked','flat','thickets','wild'],
        'Swampland M': ['warm','wet','hilly','thickets','dangerous'],
        'Taiga': ['cool','balanced','hilly','forested','calm'],
        'Taiga M': ['cool','balanced','hilly','forested','wild'],
        'TaigaHills': ['cool','balanced','hilly','forested','calm'],
    },
    'MOC': {
        'WyvernBiome': []
    }
}

